DROP DATABASE IF EXISTS HUNTDB;

CREATE DATABASE HUNTDB;

use HUNTDB;

CREATE TABLE USER
(
    USER_ID int NOT NULL AUTO_INCREMENT,
    USER_EMAIL varchar (255) NOT NULL,
    USER_PASS varchar (60) NOT NULL,
    USER_BEST int NOT NULL,
    PRIMARY KEY(PLAY_ID)
);

